all:
  children:
    proxmox_nodes:
      hosts:
        rhou-pc-msi:
          ansible_host: 100.96.73.124  # Ryan MSI PC
        joshg-pc-rog:
          ansible_host: 100.123.48.14  # Josh Beefy PC Partition
        joshg-laptop-xps:
          ansible_host: 100.72.247.56  # Josh XPS Laptop
        #joshg-laptop-blade:
        #  ansible_host: 192.168.2.103  # Josh Razer Blade Laptop
    #k3s_server:
    #  hosts:
    #    k3s-master:
    #      ansible_host: 192.168.1.104
    #k3s_agents:
    #  hosts:
    #    k3s-worker1:
    #      ansible_host: 192.168.1.101
    #    k3s-worker2:
    #      ansible_host: 192.168.1.102
    #    k3s-worker3:
    #      ansible_host: 192.168.1.103
